### ISSUE TITLE
App crashes 

### ISSUE THREAD

**Issue by enwokoma** [Charlieras262/BeatPlayer#27]
Another weird behavior is that, the app crashes on startup
Here is a logcat from the crash on Android 10 

`2020-08-24 07:10:42.127 21616-21616/com.crrl.beatplayer.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.crrl.beatplayer.dev, PID: 21616
    java.lang.IllegalStateException: BitmapFactory.decodeReso….drawable.ic_empty_cover) must not be null
        at com.crrl.beatplayer.utils.GeneralUtils.getAlbumArtBitmap(GeneralUtils.kt:164)
        at com.crrl.beatplayer.playback.players.BeatPlayerImplementation.setMetaData(BeatPlayer.kt:357)
        at com.crrl.beatplayer.playback.players.BeatPlayerImplementation.restoreQueueData(BeatPlayer.kt:328)
        at com.crrl.beatplayer.playback.players.MediaSessionCallback.setSavedMediaSessionState(MediaSessionCallback.kt:200)
        at com.crrl.beatplayer.playback.players.MediaSessionCallback.onCustomAction(MediaSessionCallback.kt:164)
        at android.support.v4.media.session.MediaSessionCompat$Callback$StubApi21.onCustomAction(MediaSessionCompat.java:1500)
        at android.support.v4.media.session.MediaSessionCompatApi21$CallbackProxy.onCustomAction(MediaSessionCompatApi21.java:259)
        at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1635)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)`

**PS:**
Building on the master branch works just fine and no crashes detected. So, it's safe to say this bug has to do with changes/commits after 05fdbf6. I hope this helps you narrow down this issue and what might be causing the app to crash.

**Comment by Charlieras262** [comment]
If you're experiencing this bug again feel free to reopen the issue.

Regards.
